max_epochs: 2000
batch_size: 64
eval_batch_size: 64
drop_rate: 0.15
device_id: 0
num_workers: 4
prefetch_factor: 4
lr: 0.0005
regularization: 0.1
weight_decay: 0.0001
T_0: 200
T_mult: 2
clip_grad_value: 5
accumulation_steps: 16
save_freq: 100
