import torch
import torch.nn.functional as F


# def lejepa_loss(pred_embed, tail_embed, a, regularization):
#     """
#     Loss function for latent-variable JEPA using Min-Distance routing.
#     Only the closest prediction generated by the sampled 'z' receives gradients.

#     Parameters
#     ----------
#     pred_embed     : Tensor [B, K, D] - K predicted embeddings from different z samples
#     tail_embed     : Tensor [B, D]    - True tail context embedding
#     a              : float            - Coefficient for regularization weight
#     regularization : callable         - External SIGReg function to prevent collapse
#     """
#     tail_frozen = tail_embed.detach()  # [B, D]

#     # Compute cosine similarity between all sampled predictions and the true target
#     cos_sim = F.cosine_similarity(
#         pred_embed, tail_frozen.unsqueeze(1), dim=-1
#     )  # [B, K]

#     # Select the best performing z sample per batch item
#     max_cos_sim, best_idx = torch.max(cos_sim, dim=-1)  # [B]
#     # rec_loss = -1 * torch.log(0.5 * (max_cos_sim + 1 + 1e-5)).mean()
#     rec_loss = (1 - max_cos_sim).mean()

#     # Extract the best predictions for collapse prevention regularization
#     batch_size = pred_embed.size(0)
#     best_pred = pred_embed[
#         torch.arange(batch_size, device=pred_embed.device), best_idx
#     ]  # [B, D]

#     # Apply external SIGReg to the chosen prediction path
#     reg_loss = regularization(torch.cat([best_pred, tail_frozen], dim=0))

#     return rec_loss + a * reg_loss, reg_loss


def lejepa_loss(pred_embed, tail_embed, a, regularization):
    """
    Loss function for latent-variable JEPA using Min-Distance routing (L2 distance).
    Only the closest prediction generated by the sampled 'z' receives gradients.

    Parameters
    ----------
    pred_embed     : Tensor [B, K, D] - K predicted embeddings from different z samples
    tail_embed     : Tensor [B, D]    - True tail context embedding
    a              : float            - Coefficient for regularization weight
    regularization : callable         - External function to prevent representation collapse
    """
    # Stop gradients from flowing into the target encoder
    tail_frozen = tail_embed.detach()  # [B, D]

    # Calculate L2 distances between all K predictions and the frozen target
    # Broadcasting: [B, K, D] - [B, 1, D] -> [B, K, D]
    distances = torch.norm(pred_embed - tail_frozen.unsqueeze(1), p=2, dim=-1)  # [B, K]

    # Route gradients only through the sample with the minimum L2 distance
    min_dist, best_idx = torch.min(distances, dim=-1)  # [B]
    rec_loss = min_dist.mean()

    # Extract the best predictions for collapse-prevention regularization
    batch_size = pred_embed.size(0)
    best_pred = pred_embed[
        torch.arange(batch_size, device=pred_embed.device), best_idx
    ]  # [B, D]

    # Apply external regularization (e.g., variance/covariance constraints)
    reg_loss = regularization(torch.cat([best_pred, tail_frozen], dim=0))

    return rec_loss + a * reg_loss, reg_loss
